# AILZ80ASM Visual Studio Code for Extensions

trigger:
  tags:
    include:
      - v*
pr: none  # no PR triggers

pool:
  vmImage: ubuntu-20.04

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'sudo npm install -g vsce'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'vsce package'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'vsce publish -p $(AILIGHTVSCE)'
